# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "deebe5274cbd75144ca06c90076f3293"
application_url = "https://vhs-require-temp-forgotten.trycloudflare.com"
embedded = true
name = "Delivery Customizations API"
handle = "delivery-customizations-api"

[build]
include_config_on_deploy = true
dev_store_url = "ilias-demo-store.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_delivery_customizations"

[auth]
redirect_urls = [
  "https://vhs-require-temp-forgotten.trycloudflare.com/auth/callback",
  "https://vhs-require-temp-forgotten.trycloudflare.com/auth/shopify/callback",
  "https://vhs-require-temp-forgotten.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
